import type { Dimension, StyleConfig } from './types';

export const DIMENSIONS: Dimension[] = [
  // Instagram
  { id: 'instagram-story', label: 'Instagram Story', width: 1080, height: 1920, category: 'Instagram' },
  { id: 'instagram-highlight', label: 'Instagram Highlight', width: 1080, height: 1920, category: 'Instagram' },
  { id: 'instagram-post-square', label: 'Instagram Post (Square)', width: 1080, height: 1080, category: 'Instagram' },
  { id: 'instagram-post-landscape', label: 'Instagram Post (Landscape)', width: 1080, height: 566, category: 'Instagram' },
  { id: 'instagram-post-portrait', label: 'Instagram Post (Portrait)', width: 1080, height: 1350, category: 'Instagram' },
  // Facebook
  { id: 'facebook-story', label: 'Facebook Story', width: 1080, height: 1920, category: 'Facebook' },
  { id: 'facebook-post', label: 'Facebook Post', width: 1200, height: 630, category: 'Facebook' },
  { id: 'facebook-cover', label: 'Facebook Cover Photo', width: 851, height: 315, category: 'Facebook' },
  { id: 'facebook-event-cover', label: 'Facebook Event Cover', width: 1920, height: 1005, category: 'Facebook' },
  // LinkedIn
  { id: 'linkedin-cover', label: 'LinkedIn Cover Photo', width: 1584, height: 396, category: 'LinkedIn' },
  { id: 'linkedin-post', label: 'LinkedIn Post', width: 1200, height: 627, category: 'LinkedIn' },
  { id: 'linkedin-story', label: 'LinkedIn Story', width: 1080, height: 1920, category: 'LinkedIn' },
  // YouTube
  { id: 'youtube-thumbnail', label: 'YouTube Thumbnail', width: 1280, height: 720, category: 'YouTube' },
  { id: 'youtube-banner', label: 'YouTube Channel Banner', width: 2560, height: 1440, category: 'YouTube' },
  // Twitter / X
  { id: 'twitter-post', label: 'Twitter/X Post', width: 1200, height: 675, category: 'Twitter/X' },
  { id: 'twitter-header', label: 'Twitter/X Header', width: 1500, height: 500, category: 'Twitter/X' },
  // TikTok
  { id: 'tiktok-video', label: 'TikTok Video', width: 1080, height: 1920, category: 'TikTok' },
  // Pinterest
  { id: 'pinterest-pin', label: 'Pinterest Pin', width: 1000, height: 1500, category: 'Pinterest' },
  { id: 'pinterest-square', label: 'Pinterest Square', width: 1000, height: 1000, category: 'Pinterest' },
  // Snapchat
  { id: 'snapchat-story', label: 'Snapchat Story', width: 1080, height: 1920, category: 'Snapchat' },
  // Standard print/other
  { id: 'a4-portrait', label: 'A4 Portrait', width: 2480, height: 3508, category: 'Print' },
  { id: 'a4-landscape', label: 'A4 Landscape', width: 3508, height: 2480, category: 'Print' },
  { id: 'square-hd', label: 'Square HD (1:1)', width: 1920, height: 1920, category: 'Other' },
  { id: 'widescreen-hd', label: 'Widescreen HD (16:9)', width: 1920, height: 1080, category: 'Other' },
];

const CARTO_ATTR = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>';
const OSM_ATTR = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';

export const STYLE_CONFIGS: StyleConfig[] = [
  {
    id: 'midnight-blue',
    label: 'Midnight Blue',
    description: 'Deep navy background with gold/copper roads – luxury atlas aesthetic',
    swatchColors: ['#0d1b2e', '#1a3a5c', 'linear-gradient(90deg, #9a7530, #c9a84c)', '#c9a84c'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(8, 16, 30, 0.90)',
    overlayText: '#c9a84c',
    posterBg: '#0d1b2e',
    accentColor: '#c9a84c',
  },
  {
    id: 'terracotta',
    label: 'Terracotta',
    description: 'Warm earthy tones with rust accents – artisan travel poster feel',
    swatchColors: ['#2d1b14', '#a89080', 'linear-gradient(90deg, #8a3d22, #c1673a)', '#c1673a'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(45, 27, 20, 0.90)',
    overlayText: '#f0d0b0',
    posterBg: '#2d1b14',
    accentColor: '#c1673a',
  },
  {
    id: 'neon',
    label: 'Neon',
    description: 'Dark canvas with electric cyan & magenta – cyberpunk city vibes',
    swatchColors: ['#00e5ff', '#0a0a14', 'linear-gradient(90deg, #7b2ff7, #c93cff)', '#c93cff'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(10, 10, 20, 0.92)',
    overlayText: '#00e5ff',
    posterBg: '#0a0a14',
    accentColor: '#c93cff',
  },
  {
    id: 'coral',
    label: 'Coral',
    description: 'Soft light map with rose & salmon tones – clean editorial style',
    swatchColors: ['#7a1528', '#d0c8c8', 'linear-gradient(90deg, #c0405a, #e8607a)', '#e8607a'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(122, 21, 40, 0.90)',
    overlayText: '#fff0f3',
    posterBg: '#1a0810',
    accentColor: '#e8607a',
  },
  {
    id: 'heatwave',
    label: 'Heatwave',
    description: 'Scorched amber & copper on dark ground – bold desert energy',
    swatchColors: ['#f5a623', '#1a0f00', 'linear-gradient(90deg, #c94000, #e85c00)', '#e85c00'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(26, 15, 0, 0.92)',
    overlayText: '#f5a623',
    posterBg: '#1a0f00',
    accentColor: '#e85c00',
  },
  {
    id: 'dark',
    label: 'Dark',
    description: 'Sleek black canvas with cool blue accents – modern minimal',
    swatchColors: ['#0a0a0a', '#1a1a2e', 'linear-gradient(90deg, #1a3a5c, #4a9eff)', '#4a9eff'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(0, 0, 0, 0.75)',
    overlayText: '#ffffff',
    posterBg: '#0a0a0a',
    accentColor: '#4a9eff',
  },
  {
    id: 'light',
    label: 'Light',
    description: 'Clean white map with indigo highlights – crisp editorial look',
    swatchColors: ['#f5f5f5', '#e0e0f0', 'linear-gradient(90deg, #2563eb, #60a5fa)', '#2563eb'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(255, 255, 255, 0.85)',
    overlayText: '#1a1a1a',
    posterBg: '#f5f5f5',
    accentColor: '#2563eb',
  },
  {
    id: 'classic',
    label: 'Classic',
    description: 'Aged parchment tones with sepia roads – vintage cartography',
    swatchColors: ['#e8d5b0', '#c9b48a', 'linear-gradient(90deg, #6b3311, #8b4513)', '#8b4513'],
    tileUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: OSM_ATTR,
    overlayBg: 'rgba(245, 230, 200, 0.88)',
    overlayText: '#3d2b1f',
    posterBg: '#e8d5b0',
    accentColor: '#8b4513',
  },
  {
    id: 'modern',
    label: 'Modern',
    description: 'Slate tones with cyan highlights – contemporary design',
    swatchColors: ['#1e293b', '#334155', 'linear-gradient(90deg, #0284a8, #06b6d4)', '#06b6d4'],
    tileUrl: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
    attribution: CARTO_ATTR,
    overlayBg: 'rgba(30, 41, 59, 0.82)',
    overlayText: '#f0f9ff',
    posterBg: '#1e293b',
    accentColor: '#06b6d4',
  },
];
